version: "3"

services:
  profile_page:
    image: profile-page-image:latest
    container_name: profile_page
    volumes:
      - /home/lyuxinghe/projects/profile_page:/home/lyuxinghe/profile_page
      - ./conf:/etc/nginx/conf.d # For nginx setting
    ports:
      - "80:80"
networks:
  my-network:
    driver: bridge